Konzole.InventorySystem.Web/Controllers/AdminController.cs
using Konzole.InventorySystem.Providers.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Konzole.InventorySystem.Web.Controllers
{
    
    public class AdminController : Controller
    {
        private IModuleProvider _moduleProvider = null;
        public AdminController(IModuleProvider moduleProvider)
        {
            this._moduleProvider = moduleProvider;
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Module()
        {
            return View(this._moduleProvider.GetList());
        }

    }
}

Konzole.InventorySystem.Web/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzole.InventorySystem;
using Konzole.InventorySystem.Providers.Interface;
using Konzole.InventorySystem.Entities;

namespace Konzole.InventorySystem.Web.Controllers
{
    public class CustomersController : Controller
    {
        private ICustomerProvider _customerProvider = null;

        public CustomersController(ICustomerProvider customerProvider)
        {
            this._customerProvider = customerProvider;
        }

        // GET: Customers
        public ActionResult Index()
        {
            return View(this._customerProvider.GetList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = this._customerProvider.GetByCustomerId(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //// GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,Contact,TIN")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                this._customerProvider.Save(customer);
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _customerProvider.GetByCustomerId(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,Contact,TIN")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerProvider.Save(customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _customerProvider.GetByCustomerId(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _customerProvider.RemoveById(id);
            return RedirectToAction("Index");
        }
    }
}

Konzole.InventorySystem.Web/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzole.InventorySystem;
using Konzole.InventorySystem.Providers.Interface;
using Konzole.InventorySystem.Web.Models;
using Konzole.InventorySystem.Entities;

namespace Konzole.InventorySystem.Web.Controllers
{
    public class SetupController : Controller
    {
        private IUOMProvider _UomProvider = null;
        private IWarehouseLocProvider _WarehouseLocProvider = null;
        private ICategoryProvider _CategoryProvider = null;
        // GET: Setup

        public SetupController(IUOMProvider UomProvider, ICategoryProvider CategoryProvider, IWarehouseLocProvider WarehouseLocProvider)
        {
            this._UomProvider = UomProvider;
            this._CategoryProvider = CategoryProvider;
            this._WarehouseLocProvider = WarehouseLocProvider;

        }


        #region UOM
        //uom
        


        [ActionName("UOMList")]
        public ActionResult UOMList()
        {
            return View(this._UomProvider.GetList());
        }

        [ActionName("UOMDetails")]
        public ActionResult UOMDetails(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UOM _uom = this._UomProvider.GetByUOMId(id);
            if (_uom == null)
            {
                return HttpNotFound();
            }
            return View(_uom);
        }


        [ActionName("CreateUOM")]
        public ActionResult CreateUOM()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUOM([Bind(Include = "Description,Abbreviation")] UOM uom)
        {
            if (ModelState.IsValid)
            {
               
                this._UomProvider.Save(uom);
                return RedirectToAction("UOMList");
            }

            return View(uom);
        }

        [ActionName("UOMEdit")]
        public ActionResult UOMEdit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UOM _uom = _UomProvider.GetByUOMId(id);
            if (_uom == null)
            {
                return HttpNotFound();
            }
            return View(_uom);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UOMEdit([Bind(Include = "Description,Abbreviation")] UOM _UOM)
        {
            if (ModelState.IsValid)
            {
                _UomProvider.Save(_UOM);
                return RedirectToAction("UOMList");
            }
            return View(_UOM);
        }
        #endregion

        #region Category
        [ActionName("CategoryList")]
        public ActionResult CategoryListing()
        {
            return View(this._CategoryProvider.GetList());
        }

        [ActionName("CategoryDetails")]
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category _category = this._CategoryProvider.GetByCategoryId(id);
            if (_category == null)
            {
                return HttpNotFound();
            }
            return View(_category);
        }


        [ActionName("CreateCategory")]
        public ActionResult CreateCategory()
        {
            return View();
        }

 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory([Bind(Include = "CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                category.Recdate = DateTime.Now;
                category.RecUser = "clarisa";
                this._CategoryProvider.Save(category);
                return RedirectToAction("CategoryList");
            }

            return View(category);
        }

        [ActionName("CategoryEdit")]
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category _category = _CategoryProvider.GetByCategoryId(id);
            if (_category == null)
            {
                return HttpNotFound();
            }
            return View(_category);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CategoryEdit([Bind(Include = "CategoryName")] Category _category)
        {
            if (ModelState.IsValid)
            {
                _CategoryProvider.Save(_category);
                return RedirectToAction("CategoryList");
            }
            return View(_category);
        }


        #endregion

        #region Warehouse location
        [ActionName("WarehouseLocList")]
        public ActionResult WarehouseListing()
        {
            return View(this._WarehouseLocProvider.GetList());
        }


        [ActionName("WarehouseDetails")]
        public ActionResult WarehouseDetails(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WarehouseLoc _Warehouse = this._WarehouseLocProvider.GetByWarehouseLocId(id);
            if (_Warehouse == null)
            {
                return HttpNotFound();
            }
            return View(_Warehouse);
        }


        [ActionName("CreateWarehouse")]
        public ActionResult CreateWarehouse()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateWarehouse([Bind(Include = "LocationAddress")] WarehouseLoc _WarehouseLoc)
        {
            if (ModelState.IsValid)
            {
                _WarehouseLoc.Recdate = DateTime.Now;
                _WarehouseLoc.RecUser = "clarisa";
                this._WarehouseLocProvider.Save(_WarehouseLoc);
                return RedirectToAction("WarehouseLocList");
            }

            return View(_WarehouseLoc);
        }

        [ActionName("WarehouseEdit")]
        public ActionResult WarehouseEdit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WarehouseLoc _Warehouse = _WarehouseLocProvider.GetByWarehouseLocId(id);
            if (_Warehouse == null)
            {
                return HttpNotFound();
            }
            return View(_Warehouse);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WarehouseEdit([Bind(Include = "LocationAddress")] WarehouseLoc _WarehouseLoc)
        {
            if (ModelState.IsValid)
            {
                _WarehouseLocProvider.Save(_WarehouseLoc);
                return RedirectToAction("WarehouseLocList");
            }
            return View(_WarehouseLoc);
        }

        #endregion


    }
}

Konzole.InventorySystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" content="" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Konzole System</title>

    @Styles.Render("~/Content/startmin")
    @Styles.Render("~/Content/bootstrap")
    @*@Styles.Render("~/Content/metisMenu")
    @Styles.Render("~/Content/timeline")*@

    @Styles.Render("~/Content/morris")
    @Styles.Render("~/Content/css/font-awesome.min.css")
    @*@Styles.Render("~/Content/Site")*@
    <!-- DataTables CSS -->
    @Styles.Render("~/Content/dataTable-style")
    @Scripts.Render("~/Content/jquery")
    <!-- DataTables JS -->
    @Scripts.Render("~/Content/dataTable-script")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style type="text/css">
        input:required:focus, select:required:focus {
            border: 1px solid red;
            outline: none;
        }

        input:required:focus, select:required:hover {
            opacity: 1;
        }

        .black-background {
            background-color: #000000;
        }

        .white {
            color: #ffffff;
        }
    </style>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-light" style="background-color: #293A48;">
            @*<ul class="nav navbar-nav navbar-left navbar-top-links">
                <li><a id="btnToggle" href="#" title="Toggle Menu" style="visibility:inherit"><i class="fa fa-angle-double-left fa-fw"></i>Menu</a></li>

            </ul>*@
            <div class="navbar-header">
                <span class="navbar-brand" href="#">Konzole System</span>
            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <ul class="nav navbar-right navbar-top-links" >
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> Setting<b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="#" data-toggle="modal" data-target="#mdLogout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- /.navbar-top-links -->
            <div id="dvMenu" class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <a>Logo Here</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                      

                        <li>
                            <a href="#"><i class="fa fa-users"></i> Accounts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                               <li><a href=@Url.Action("Index", "Suppliers")><i class="fa fa-dashboard fa-fw"></i> Supplier</a></li> 
                                <li><a href=@Url.Action("Index", "Customers")><i class="fa fa-dashboard fa-fw"></i> Customer</a></li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-cubes"></i> Inventory<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Product</a></li>
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Inventory</a></li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-shopping-cart"></i> Purchasing<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Purchase Orders</a></li>
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Receive Orders</a></li>
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Bills</a></li>
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Purchase Returns</a></li>
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Payments</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="#" }><i class="fa fa-tags"></i> Sales</a>
                        </li>
                        <li>
                            <a href="#" }><i class="fa fa-area-chart"></i> Report</a>
                        </li>
                        <li>
                     
                            <a href="#"><i class="fa fa-cogs"></i> Setting<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="#"><i class="fa fa-dashboard fa-fw"></i> Company Setup</a></li>
                                <li><a href=@Url.Action("WarehouseLocList", "Setup")><i class="fa fa-dashboard fa-fw"></i> Warehouse Location</a></li>
                                <li><a href=@Url.Action("CategoryList", "Setup")><i class="fa fa-dashboard fa-fw"></i> Categories</a></li>
                                <li><a href=@Url.Action("UOMList", "Setup")><i class="fa fa-dashboard fa-fw"></i> Unit of Measurements</a></li>
                            </ul>
                        </li>
                       
                        <li>

                            <a href="#"><i class="fa fa-user"></i> Admin<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href=@Url.Action("Index", "Admin")><i class="fa fa-dashboard fa-fw"></i> User</a></li>
                                <li><a href=@Url.Action("Index", "Admin")><i class="fa fa-dashboard fa-fw"></i> Add Roles</a></li>
                            </ul>
                        </li>

                        

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
           <!-- Page Content -->
        @RenderBody()
        <!-- /#page-wrapper -->
        
     
    </div>
    <!-- /#wrapper -->

    <div class="modal fade" id="mdLogout" tabindex="-1" role="dialog" aria-labelledby="mdLogoutLabel" aria-hidden="true">
        <div class="modal-dialog" style="width:350px;top:250px;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="btnCloseLogout" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mdLogoutLabel">User Log out</h4>
                </div> <!-- /.modal-header -->

                <div class="modal-body">
                    Are you sure you want to log-out?<br />
                    <span style="font-size:9px;">Note: Currect running time will be lost.</span>
                </div> <!-- /.modal-body -->

                <div class="modal-footer">
                    @*@Html.ActionLink("Logout", "LogOff", "Account", routeValues: new { area = "" }, htmlAttributes: new { @class = "btn btn-success", @style = "width:150px;" })*@
                    <button id="btnCancel" class="form-control btn btn-danger" data-dismiss="modal" style="width:150px;">Cancel</button>
                </div> <!-- /.modal-footer -->

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    @Scripts.Render("~/Content/js")
 
    @Scripts.Render("~/Content/scripts/jquery-ui.js")
    @Styles.Render("~/Content/css/jquery-ui.css")
    @*<script type="text/javascript">
            $("#btnToggle").click(function (e) {

                if ($("#dvMenu").is(':visible')) {
                    $(this).html('<i class="fa fa-angle-double-right fa-fw"></i>Menu');
                    $("#dvMenu").fadeOut();
                    $("#page-wrapper").animate({ "margin-left": '0' });
                }
                else {
                    $(this).html('<i class="fa fa-angle-double-left fa-fw"></i>Menu');
                    $("#page-wrapper").animate({ "margin-left": '250px' });
                    $("#dvMenu").fadeIn();
                }

            });
    </script>*@
</body>

</html>