Konzole.InventorySystem.Web/Controllers/Api/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Konzole.InventorySystem.Providers.Interface;

namespace Konzole.InventorySystem.Web.Controllers.Api
{
    public class SupplierController : ApiController
    {
        ISupllierProvider _supplierprovider = null;

        public SupplierController(ISupllierProvider _supplierProvider)
        {
            this._supplierprovider = _supplierProvider;
        }

        public HttpResponseMessage GetList()
        {
            return this.BuildResponse(HttpStatusCode.OK, _supplierprovider.GetList());
        }

        public HttpResponseMessage Get(int id)
        {
            return this.BuildResponse(HttpStatusCode.OK, _supplierprovider.GetBySupplierId(id));
        }

        public HttpResponseMessage Post(Supplier supplier)
        {
            if (_supplierprovider.Save(supplier))
            {
                var locationHeaderValue = "/api/Supplier/" + supplier.Id;
                return this.BuildResponse(HttpStatusCode.Created, supplier, locationHeaderValue);
            }

            return Request.CreateResponse(HttpStatusCode.InternalServerError);
        }

        public HttpResponseMessage Put(Supplier supplier)
        {
            if (_supplierprovider.Save(supplier))
            {
                return this.BuildResponse(HttpStatusCode.OK, supplier);
            }

            return this.BuildResponse(HttpStatusCode.NotFound);
        }

        public HttpResponseMessage Delete(int id)
        {
            Supplier supplier = _supplierprovider.GetBySupplierId(id);
            //customer.SetIsActivate(false);

            if (_supplierprovider.Save(supplier))
            {
                return this.BuildResponse(HttpStatusCode.OK, supplier);
            }

            return this.BuildResponse(HttpStatusCode.NotFound);
        }
    }
}

Konzole.InventorySystem.Web/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzole.InventorySystem;
using Konzole.InventorySystem.Providers.Interface;
using Konzole.InventorySystem.Web.Models;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using Konzole.InventorySystem.Infrastructure;

namespace Konzole.InventorySystem.Web.Controllers
{
    public class SuppliersController : Controller
    {
        private ISupllierProvider _supplierProvider = null;


        public SuppliersController(ISupllierProvider supplierProvider)
        {
            this._supplierProvider = supplierProvider;
        }

        // GET: Suppliers
        public ActionResult Index()
        {
            return View(this._supplierProvider.GetList());
        }

        // GET: Suppliers/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = this._supplierProvider.GetBySupplierId(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // GET: Suppliers/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SupplierName,Address,Contact,Status")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                this._supplierProvider.Save(supplier);
                return RedirectToAction("Index");
            }

            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = _supplierProvider.GetBySupplierId(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SupplierName,Address,Contact,Status")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _supplierProvider.Save(supplier);
                return RedirectToAction("Index");
            }
            return View(supplier);
        }


        // GET: Suppliers/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = _supplierProvider.GetBySupplierId(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _supplierProvider.RemoveById(id);
            return RedirectToAction("Index");
        }

        [ActionName("SupplierNavigator")]
        public ActionResult fncGetResumeNavigation()
        {
            return PartialView();
        }


        [ActionName("SupplierScripts")]
        public PartialViewResult fncGetJavaScriptForResumeBuilder()
        {
            return PartialView();
        }



        //[Authorize]
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Search")]
        public ActionResult GenerateGrid()
        {
            
            IEnumerable<Supplier> data = this._supplierProvider.GetList();
            return View(data);
        }

        //[Authorize]

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Export")]
        public ActionResult ExportToExcel()
        {
            

            GridView gv = new GridView();

            var data = this._supplierProvider.GetList();
            gv.DataSource = data.Select(a => new Supplier
            {
                SupplierName = a.SupplierName,
                Address = a.Address,
                Contact = a.Contact,
                Email = a.Email
            });

            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=Supplier.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();
            gv = null;

            return View(data);
        }
    }
}

Konzole.InventorySystem.Web/Views/Suppliers/Create.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Konzole.InventorySystem.Web/Views/Suppliers/Details.cshtml
@model Konzole.InventorySystem.Supplier

@{
    ViewBag.Title = "View Supplier Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





@{
    <style type="text/css">
        @@media(min-width: 992px) {
            .nav-close {
                display: none;
            }
        }

        @@media(max-width: 991px) {
            .nav-wide {
                display: none;
            }

            .main-wide {
                width: 100%;
            }
        }

        .sReq {
            color: #DA2727;
            font-size: medium;
        }

        .resume-no-margin-top {
            margin: 0px !important;
            clear: both;
        }

        .resume-no-margin {
            padding: 1px;
            margin: 0px !important;
            font-size: 12px;
        }

        i {
            color: #888484;
        }

        .nav-span {
            position: absolute;
            margin-top: -5px;
        }

        .parentDiv {
            @* box-shadow: 0px 10px 30px 10px rgba(235,228,235,1);
            border-radius: 5px;
            *@;
        }

        .nav-stacked > li {
            box-shadow: 0px 10px 30px 10px rgba(235,228,235,0.18);
            border-radius: 5px;
        }

        g {
            color: red;
            font-size: smaller;
        }

        .resume-stack-submit {
            position: fixed;
            bottom: -7px;
            background-color: rgb(130, 197, 86);
            z-index: 1;
            padding: 10px;
            text-align: right;
            right: 0px;
            @* position: fixed;
            bottom: -7px;
            background-color: rgb(255, 255, 255);
            /* width: 54%; */
            border-radius: 0.5em;
            z-index: 1;
            padding: 10px;
            text-align: right;
            background: linear-gradient(to right, rgba(0, 0, 0, 0), #E6E6E6);
            right: 50px;
            /* padding-top: 50px; */
            padding: 20px 10px 20px 50px;
            width: 50%;
            position: fixed;
            bottom: 10px;
            background-color: rgb(255, 255, 255);
            width: 54%;
            border-radius: 0.5em;
            z-index: 1;
            padding: 10px;
            text-align: right;
            background: linear-gradient(to right, rgba(0, 0, 0, 0), #E6E6E6);
            *@;
        }

        .resume-unstack-submit {
            background-color: rgb(255, 255, 255);
            width: 100%;
            border-radius: 0.5em;
            z-index: 1;
            padding: 10px;
            background: linear-gradient(to right, rgba(0, 0, 0, 0), #E6E6E6);
        }

        .nav-stacked > li > a {
            color: rgb(111, 95, 90);
            padding: 5px 3px;
        }

        .panel > a:hover, .panel > a:focus {
            text-decoration: none;
        }


        .panel > a {
            color: White;
        }


        legend {
            color: white;
            font-size: 20px;
            background-color: #1c9a48;
            padding: 15px;
            border: 0;
            font-family: "QuireSansW04-ExtraLight";
            padding: 15px;
            font-size: 23px;
        }


        h4 {
            color: rgb(152,207,22);
        }

        hr {
            display: block;
            height: 1px;
            border: 0;
            border-top: 1px solid rgb(152,207,22);
            margin: 1em 0;
            padding: 0;
        }

        .wrapper {
            min-width: 500px;
            padding: 0 15px;
        }

        .navigation {
            position: fixed;
        }

        .content {
        }

        panel-group .panel {
            margin-bottom: 0;
            /* border-radius: 4px; */
            border: none;
        }

        .resume-panel-heading {
            color: white;
            padding: 15px;
            /* border-top-left-radius: 5px; */
            /* border-top-right-radius: 5px; */
            margin-bottom: 0;
            font-size: 20px;
            font-family: "QuireSansW04-ExtraLight";
            font-size: 23px;
        }

        .collapse-nav > .resume-panel-heading {
            background: #82c556;
        }

        .collapsed > .resume-panel-heading {
            background: #e5f3db;
            color: #89c85f;
        }

        .panel {
            border: none;
        }

        .none {
            padding: 0;
            margin 0;
        }

    
    </style>
}


    <div class="col-sm-12 none">
        <div class="none ">
            @Html.Action("SupplierNavigator", "Suppliers")
        </div>
        @* <div class="col-sm-3"><br clear="both" /></div>*@
        <div class="col-sm-8 none main-wide">
            <div id="divResumeData">
          
                                    <div class="row">
                                        <div class="col-lg-12">

                                            <div class="form-group">
                                               
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier Id:</label>
                                                @Html.TextBoxFor(model => model.Id, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier Name:</label>
                                                @Html.TextBoxFor(model => model.SupplierName, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier Address:</label>
                                                @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier Contact:</label>
                                                @Html.TextBoxFor(model => model.Contact, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier Email:</label>
                                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier EWT:</label>
                                                @Html.TextBoxFor(model => model.EWTId, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier VAT:</label>
                                                @Html.TextBoxFor(model => model.VATtypeId, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Payment Term:</label>
                                                @Html.TextBoxFor(model => model.Terms, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>

                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Payment Term:</label>
                                                @Html.TextBoxFor(model => model.Terms, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Tax Code:</label>
                                                @Html.TextBoxFor(model => model.Taxcode, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Payment Term:</label>
                                                @Html.TextBoxFor(model => model.Terms, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Supplier Status:</label>
                                                @Html.TextBoxFor(model => model.Status, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Created By:</label>
                                                @Html.TextBoxFor(model => model.Recuser, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Created Date:</label>
                                                @Html.TextBoxFor(model => model.Recdate, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Modified By:</label>
                                                @Html.TextBoxFor(model => model.Moduser, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-4" style="text-align:right; font-weight:normal;">Date Modified:</label>
                                                @Html.TextBoxFor(model => model.ModDate, new { @class = "form-control", @style = "width:350px", @readonly = "readonly" })
                                            </div>

                                        </div>
                                        <!-- /.col-lg-12 (nested) -->
                                    </div>
                                    <!-- /.row (nested) -->

        </div>

            <div class="form-group">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
    </div>
@Html.Action("SupplierScripts", "Suppliers")
 

Konzole.InventorySystem.Web/Views/Suppliers/Index.cshtml
@model IEnumerable<Konzole.InventorySystem.Supplier>
@{
    ViewBag.Title = "Supplier Details";
   
}
<div id="page-wrapper">
        
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                          

                            @using (Html.BeginForm())
                            {
                                <div class="form-group">
                                    @Html.ActionLink("Add New", "Create", new { controller = "Supplier" }, htmlAttributes: new { @class = "btn btn-success" })

                                    <input type="submit" class="form-control btn btn-success" style="width:120px;" value="Export" name="action" /> 
                                </div>
     

                                <div class="form-group">
                                    <label class="col-lg-1" style="width:110px;">Supplier (optional)</label>
                                    @Html.TextBox("SupplierName","", new { @class = "form-control col-lg-9", @style = "width:200px;" })
                                  </div>

                                <div class="form-group">
                                    <input type="submit" class="form-control btn btn-primary" style="width:120px;" value="Search" name="action" /> 
                                 </div>

                                <div class="form-group">
                                    <label class="col-lg-1" style="width:110px;">Status</label>
                                    @Html.TextBox("Status", "", new { @class = "form-control col-lg-9", @style = "width:200px;" })
                                </div>


                                <span class="loaders reports-load"></span>
                                <table class="table table-striped table-bordered table-hover" id="dataTables-transactionLogs">
                                    <thead>
									    <tr>
                                            <th>&nbsp; </th>
										    <th>SupplierName </th>
										    <th>Address </th>
										    <th>Contact </th>
										    <th>Email </th>
                                            <th>Date Created </th>
										    <th>Status </th>
									    </tr>
								    </thead>
								    <tbody id="tblTrans-Body">
                                        @foreach (var row in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = row.Id }) |
                                                    @Html.ActionLink("Details", "Details", new { id = row.Id }) |
                                                    @Html.ActionLink("Delete", "Delete", new { id = row.Id })
                                                </td>
                                                <td class="center">@row.SupplierName</td>
                                                <td>@row.Address</td>
                                                <td>@row.Contact</td>
                                                <td>@row.Email</td>
                                                <td>@row.Recdate</td>
                                                <td>@row.Status</td>
                                              
                                            </tr>
                                        }
								    </tbody>    
                                </table>
                            }
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->
    @*@Scripts.Render("~/Content/scripts/custom/transactionLog.js")*@
    <script type="text/javascript">
       
        $('#dataTables-transactionLogs').DataTable({
            responsive: true
        });
    </script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->

Konzole.InventorySystem.Web/Views/Suppliers/SupplierNavigator.cshtml
@model Konzole.InventorySystem.Supplier

<style type="text/css">
    a#showLeftPush.a-nav-open {
        background: rgba(255, 255, 255, 0);
    }

    .arrow-right {
        /* width: 0; */
        height: 0;
        border-top: 30px solid transparent;
        border-bottom: 30px solid transparent;
        border-left: 30px solid green;
        border-left: 30px solid #82c556;
        margin-left: 26px;
    }


    .arrow-left {
        /* width: 0; */
        height: 0;
        border-top: 30px solid transparent;
        border-bottom: 30px solid transparent;
        border-left: 30px solid #82c556;
        margin-left: 26px;
    }

    .dv-rotate {
        background-color: #82c556;
        color: white;
        -ms-transform: rotate(270deg);
        -webkit-transform: rotate(270deg);
        transform: rotate(270deg);
        margin-left: 9.4px;
        padding: 7px;
    }

    .btn-primary1:hover, .btn-primary1:focus, .btn-primary2:hover, .btn-primary2:focus {
        background-color: #1c9a48 !important;
        background-position: 0 -15px;
    }

    .btn-primary1 {
        padding: 5px !important;
        width: 100px;
        float: right;
        border: 2px solid #ffffff !important;
        color: white !important;
    }

    .btn-primary2 {
        padding: 3px 0px !important;
        width: 80px;
        border: 2px solid #ffffff !important;
        color: white !important;
        font-size: small !important;
    }
</style>
<div class="nav-close">
    <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
        <table style="width: 100%; background-color: #3d7440;">
            <tr>
                <td>
                    <h3>
                        My Supplier
                    </h3>
                </td>
                <td>
                    <div id="objForSaveOnly">
                        <a onclick="mtdExtractResume()" class="btn btn-primary btn-primary2">
                            <i class="fa fa-inbox"
                               style="color: white;"></i>&nbsp;EXTRACT
                        </a>
                    </div>
                </td>
            </tr>
        </table>
        <a class="lnkResumeLeft lnkResumeNavigator" href="#">
            <span class="resume-sprite pd-icon"></span>Personal Details
            <g>(Required)</g>
        </a><a class="lnkResumeLeft lnkResumeNavigator" href="#">
            <span class="resume-sprite add-icon"></span>Address
            <g>(Required)</g>
        </a><a class="lnkResumeLeft lnkResumeNavigator" href="#">
            <span class="resume-sprite fmd-icon"></span>Family Members / Dependents
        </a>
        
        <a id="showLeftPush" class="a-nav-open">
            <div class="dv-rotate">
                <i class="fa fa-bars" style="color: white;"></i>MENU
            </div>
        </a>
    </nav>
   
</div>

<div class="left-panel col-md-4 nav-wide">
    <div class="col-md-12 no-gutter">
        <div id="my-resume">
            <table style="width: 100%">
                <tr>
                    <td>
                        <p>
                            My Supplier
                        </p>
                    </td>
                    <td>
                        <div id="objForSaveOnly">
                            <a onclick="mtdExtractResume()" class="btn btn-primary btn-primary1">
                                <i class="fa fa-inbox"
                                   style="color: white;"></i>&nbsp;EXTRACT
                            </a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <a id="lnkPersonalDetails" class="lnkResumeNavigator" href="#">
            <span class="resume-sprite pd-icon"></span>Supplier Details

        </a><a id="lnkAddess" class="lnkResumeNavigator" href="#">
            <span class="resume-sprite add-icon"></span>Supplier Contacts
     
        </a><a id="lnkDependents" class="lnkResumeNavigator" href="#">
            <span class="resume-sprite fmd-icon"></span>Supplier Purchase Order
        </a>
        <a id="lnkEmployedRelatives" class="lnkResumeNavigator" href="#">
            <span class="resume-sprite re-icon"></span>Supplier Payment
        </a><a class="lnkResumeNavigator" href="#">
            <span class="resume-sprite eb-icon"></span>Supplier Returns
           
      
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
       
    });
</script>